language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.4
script:
  - "rake spec SPEC_OPTS='--format documentation'"
env:
  - PUPPET_VERSION="~> 3.1.1"
  - PUPPET_VERSION="~> 3.2.4"
  - PUPPET_VERSION="~> 3.3.2"
  - PUPPET_VERSION="~> 3.4.3"
  - PUPPET_VERSION="~> 3.5.1"
  - PUPPET_VERSION="~> 3.6.2"
  - PUPPET_VERSION="~> 3.7.3"
matrix:
  exclude:
    - rvm: 2.0.0
      env: PUPPET_VERSION="~> 3.1.0"
      gemfile: .gemfile
    - rvm: 2.1.4
      env: PUPPET_VERSION="~> 3.1.0"
      gemfile: .gemfile
    - rvm: 2.1.4
      env: PUPPET_VERSION="~> 3.2.0"
      gemfile: .gemfile
    - rvm: 2.1.4
      env: PUPPET_VERSION="~> 3.3.0"
      gemfile: .gemfile
    - rvm: 2.1.4
      env: PUPPET_VERSION="~> 3.4.0"
      gemfile: .gemfile

gemfile: .gemfile
notifications:
  email:
    - romain42@gmail.com
