name 'example42-shinken'
version '2.0.10'

author 'Romain THERRAT'
license 'Apache2'
project_page 'http://www.example42.com'
source 'https://github.com/lermit/puppet-shinken'
summary 'Puppet module for shinken'
description 'This module installs and manages shinken. Check README for details.'
dependency 'example42/puppi', '>=2.0.0'
dependency 'example42/firewall', '>=2.0.0'
dependency 'example42/monitor', '>=2.0.0'
